// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function GetArgs() {
  return window['go']['main']['App']['GetArgs']();
}

export function LaunchAndExit(arg1) {
  return window['go']['main']['App']['LaunchAndExit'](arg1);
}

export function RunUpdate() {
  return window['go']['main']['App']['RunUpdate']();
}
