// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exit():Promise<void>;

export function GetArgs():Promise<Record<string, any>>;

export function LaunchAndExit(arg1:string):Promise<void>;

export function RunUpdate():Promise<void>;
